3mdeb/news-and-ideas

post.md
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
@pietrushnic Split post into a series
=> flashing eMMC on HB Edge - part 1: initial commit

post.md
=> re-adding post.md file

post.md
=> removed permalink

post.md
=> wordpress github sync

post.md
re-uploading the post.md due to error
=> move emmc blog post to post.md again

post.md
Corrected the language mistakes.
=> typos and grammar correction

_posts/2018-07-27-Our-first-look-at-debos-new-Debian-images-generator.md, post.md
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> post.md: add debos post

_posts/2018-08-04-pfsense-as-hvm-on-pc-engines-apu2.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> pfsense_hvm: initial commit

README.md
@pietrushnic @miczyg1 If you have noticed anything that needs to be corrected or added/clarified, please write it down here.
=> corrected date format and added note about post_title

README.md, _posts/YYYY-MM-DD-template-post.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> add temaplate post

_posts/2018-08-14-apu2-validation-with-rte.md
TO DO: add 2 (or more) images of RTE+APU setup for article
=> apu2-validation-with-rte post

_posts/2018-08-22-optimize-performance-in-docker.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> docker_perf: initial commit

_posts/2018-10-09-enabling-ecc-on-pc-engines-apu2.md
=> enabling-ecc-on-pc-engines-apu2.md: add post

_posts/2019-03-XX-roca.md, _posts/2019-04-XX-roca.md
=> 2019-03-XX-roca.md: ROCA TPM vulnerability

scripts/build.sh
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> build.sh: change img path to blog/img

scripts/build.sh
Reverts 3mdeb/news-and-ideas#64
=> Revert "build.sh: change img path to blog/img"

blog/themes/3mdeb/static/css/bulma.css
=> blog/themes/3mdeb/static/css/bulma.css: add min-heigth for author image

blog/content/post/2019-06-07-muxpi-validation-kit.md
=> blog/content/post/2019-06-07-muxpi-validation-kit.md: change publish date

blog/data/authors/tomasz.zyjewski.json
=> add tomasz profile

blog/content/post/2019-06-12-Hummingboard-Pulse-first-impression.md
=> blog/content/post/2019-06-12-Hummingboard-Pulse-first-impression.md: fix formatting

blog/content/post/2019-06-09-muxpi-validation-kit.md
=> blog/content/post/2019-06-09-muxpi-validation-kit.md: fix archive

blog/content/post/2019-06-21-rte-new-version-and-kit.md
=> blog/content/post/2019-06-21-rte-new-version-and-kit.md: fix shop link

blog/content/post/2019-07-11-how-to-safely-and-easily-update-your-firmware.md
=> blog/content/post/2019-07-11-how...: fix actual date

blog/content/post/2019-03-08-Flashing-emmc-on-hummingboard-edge-using-fastboot-part-2.md
This should fix the broken mobile layout.
=> blog/content/post/2019-03-08-…md: add abstract

blog/themes/3mdeb/layouts/post/single.html
https://jira-3mdeb.atlassian.net/browse/CM-552
=> blog:/ added podcast to posts

blog/content/post/2013-07-30-improve-productivity-with-goolge-history-using-bookmarks-and-chrome-extensions.md
=> blog/content/post/2013-07-30: add link for updated analysis

blog/content/post/2019-08-07-qubes-os-and-3mdeb-minisummit.md, blog/content/post/YYYY-MM-DD-template-post.md
=> blog/content/post/: fix title for JSON database

blog/content/post/2019-08-07-qubes-os-and-3mdeb-minisummit.md
=> blog/content/post/2019-08-07: fix doubled line

README.md
=> README.md: add guide for creating new profile pages

blog/themes/3mdeb/layouts/post/single.html
Reverts 3mdeb/news-and-ideas#137
=> Revert "widget podcast excludes code blocks"

blog/content/post/2019-05-29-spectre-and-meltdown-on-apu2.md
=> blog/content/post/2019-05-29: fix text formatting

blog/themes/3mdeb/layouts/post/single.html
=> blog/themes/3mdeb/layouts/post/single.html: set widget url to prod

blog/content/authors/lukasz-wcislo/_index.md, blog/themes/3mdeb/layouts/authors/list.html
=> blog/themes/3mdeb/layouts/authors/list.html: fix social media header

blog/static/.htaccess
=> blog/static/.htaccess: rollback to production url

blog/content/authors/piotr-kleinschmidt/_index.md, blog/data/authors/piotr.kleinschmidt.json, blog/themes/3mdeb/layouts/partials/widget-authors.html
=> blog/: add Piotr missing profile files and info

README.md
=> README.md: use hugo-builder with 0.54 version due to issue with 0.55

blog/themes/3mdeb/layouts/partials/header.html
=> blog/themes/3mdeb/layouts/partials/header.html: add SEO script

blog/content/post/2019-12-13-pfsense-boot-under-xen.md
=> pfSense implementation under Xen hypervisor - boot optimization

blog/content/post/2019-11-06-pfsense-under-xen-introduction.md, blog/content/post/2019-12-13-pfsense-boot-under-xen.md
=> 2019-11-06-pfsense; 2019-12-13-pfsense: Add parts to titles

README.md, blog/content/post/YYYY-MM-DD-template-post.md, scripts/new-post.sh
=> scripts/: add new-post script

blog/content/post/2012-03-20-building-arm-toolchain-part-1-libs-and-binutils.md, blog/content/post/2012-04-06-how-to-download-videos-from-videos-linux-com.md, blog/content/post/2012-04-12-building-arm-toolchain-part-2-gcc-and-eglibc.md, blog/content/post/2012-05-13-mutt-tutorial-part-1-setup-imap-account.md
=> blog/content/post/2012*: fix post formatting

blog/themes/3mdeb/static/css/bulma.css
=> Post list css fix

scripts/new-post.sh
=> scripts/new-post.sh: fix tags indentation

README.md
=> lang highlight readme

blog/themes/3mdeb/layouts/partials/footer.html
=> blog/themes/3mdeb/layouts/partials/footer.html: update year

blog/content/post/2019-12-12-vmx-exit-reasons-and-handlers.md, blog/content/post/2020-01-23-vmx-exit-reasons-and-handlers.md
=> 2019-12-12-vmx-exit-reasons-and-handlers.md: add post

blog/content/post/2017-11-02-pc-engines-apu2-python-robot-framework-validation-automation.md
=> blog/content/post/2017-11-02: add backlink to external post

README.md
=> README.md: fix formatting

blog/content/authors/pawel-zaborny/_index.md, blog/data/authors/pawel.zaborny.json
=> blog/: add template for new profile

blog/content/post/2020-02-18-ew2020-btg-demo.md
=> Boot Guard post: change Protectli link and fix spaces

blog/content/post/2020-02-18-ew2020-btg-demo.md
=> blog/content/post/2020-02-18: add subsidy info

blog/content/post/2020-03-04-esxi-67-boot-issue-part1.md
=> blog/content/post/2020-01-03: change publish date

blog/themes/3mdeb/layouts/partials/widget-authors.html
=> partials/widget-authors.html: fix sort by articles number

blog/content/post/2019-02-14-enabling-cpb-on-pcengines-apu2.md, blog/content/post/2019-03-08-Flashing-emmc-on-hummingboard-edge-using-fastboot-part-2.md, blog/content/post/2019-03-14-meltdown-and-spectre-vulnerabilities.md, blog/content/post/2019-04-17-roca.md, blog/content/post/2019-04-30-5-terms-every-hypervisor-developer-should-know.md, blog/content/post/2019-05-08-bit-bang-theory-with-rte.md, blog/content/post/2019-05-15-building-bareflank.md, blog/content/post/2019-05-22-reproducible-builds.md, blog/content/post/2019-05-29-spectre-and-meltdown-on-apu2.md, blog/content/post/2019-06-07-muxpi-validation-kit.md, blog/content/post/2019-06-12-Hummingboard-Pulse-first-impression.md, blog/content/post/2019-06-21-rte-new-version-and-kit.md, blog/content/post/2019-06-26-smallest-embedded-system-yocto-vs-buildroot.md, blog/content/post/2019-07-11-how-to-safely-and-easily-update-your-firmware.md, blog/content/post/2019-07-24-esp8266-quick-guide-for-embedded-c-developers.md, blog/content/post/2019-08-07-qubes-os-and-3mdeb-minisummit.md, blog/content/post/2019-08-19-3mdeb-roadmap.md, blog/content/post/2019-09-06-embedded-systems-consulting-insiders-view.md, blog/content/post/2019-10-22-psec-2019.md, blog/content/post/2019-11-06-pfsense-under-xen-introduction.md, blog/content/post/2019-11-22-Websummit-2019.md, blog/content/post/2019-12-13-pfsense-boot-under-xen.md, blog/content/post/2020-01-10-genode.md, blog/content/post/2020-01-23-vmx-exit-reasons-and-handlers.md, blog/content/post/2020-02-18-ew2020-btg-demo.md, blog/content/post/2020-02-19-GRUB2_and_3mdeb_minisummit.md, blog/content/post/2020-03-04-esxi-67-boot-issue-part1.md, blog/content/post/YYYY-MM-DD-template-post.md
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
=> blog/content/post: fix typo in sign ip for newsletter link

blog/content/post/2020-03-28-trenchboot-nlnet-introduction.md
=> blog/content/post/2020-03-24: rename and use unordered list

blog/content/post/2020-04-03-trenchboot-nlnet-lz-validation.md
=> 2020-04-03-trenchboot-nlnet-lz-validation.md: change title

blog/content/post/2020-04-16-3mdeb-contrib-Q1.md
=> blog/content/post/2020-04-16: fix indented list

blog/themes/3mdeb/static/css/blog.css
Fixed overlapping icon from websitevoice.com
=> 3mdeb/static/css/blog.css: fixed overlapping icon

blog/themes/3mdeb/static/css/bulma.css
=> 3mdeb/static/css/bulma.css: ul indented with ol fix

blog/themes/3mdeb/static/css/bulma.css
=> 3mdeb/static/css/bulma.css: post-summary and cover fix  for <480px

blog/themes/3mdeb/layouts/authors/list.html, blog/themes/3mdeb/layouts/authors/terms.html
=> 3mdeb/layouts/authors/[list/terms].html: fixed missing footer

blog/themes/3mdeb/static/css/blog.css, blog/themes/3mdeb/static/css/bulma.css
=> 3mdeb/static/css/blog.css: fixed <table> overflow

blog/themes/3mdeb/layouts/partials/header.html, blog/themes/3mdeb/static/css/blog.css, blog/themes/3mdeb/static/css/bulma.css
=> 3mdeb/static/css/bulma.css: author-cover and desc layout fixes

blog/content/post/2020-05-05-trenchboot-nlnet-ci-cd-system.md
=> 2020-05-05-trenchboot-nlnet-ci-cd-system.md fix images dirs

blog/content/post/2020-05-05-trenchboot-nlnet-ci-cd-system.md
=> post/2020-05-05-trenchboot-nlnet-ci-cd-system.md: center img labels

blog/content/post/2020-05-05-trenchboot-nlnet-ci-cd-system.md
=> post/2020-05-05-trenchboot-nlnet-ci-cd-system.md: center last img label

blog/themes/3mdeb/static/css/bulma.css
=> 3mdeb/static/css/bulma.css: added min-width to search input

blog/content/authors/michal-zygowski/_index.md, blog/data/authors/michal.zygowski.json
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
=> blog/data/authors/michal.zygowski.json: update BIO

blog/content/authors/piotr-krol/_index.md, blog/data/authors/piotr.krol.json
=> blog/: update Piotr's profile

blog/content/post/2020-05-15-qubesOs.md
=> post/2020-05-15-qubesOs.md: fix last name

blog/content/post/2020-06-01-ipxe_lz_support.md
=> 2020-06-01-ipxe_lz_support.md: add info about CSM being required

blog/content/post/2020-04-03-trenchboot-nlnet-lz-validation.md
=> 2020-04-03-trenchboot-nlnet-lz-validation.md: add TPM1.2 requirement verification

blog/content/post/2020-07-01-dev_and_iommu.md, blog/content/post/2020-07-03-dev_and_iommu.md
=> post/2020-07-01-dev_and_iommu.md: post about IOMMU issue after SKINIT

blog/content/post/2020-07-23-secure-app-coding-practices.md
=> post/2020-07-23-secure-app-coding-practices.md: wrap and change word

blog/content/post/2020-08-31-booting-coreboot-on-cometlake.md
=> post/2020-08-31-booting-coreboot-on-cometlake.md: change release date

blog/content/post/2020-09-17-qubes_fwupd_heads_uefi.md, blog/content/post/2020-09-18-qubes_fwupd_heads_uefi.md
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
=> qubes-fwupd - system firmware update methods

blog/content/post/2020-10-13-xen-implementation-for-trenchboot.md, blog/content/post/2020-10-15-xen-implementation-for-trenchboot.md
Signed-off-by: Norbert Kaminski <norbert.kaminski@3mdeb.com>
=> Xen hypervisor support for the TrenchBoot

blog/content/post/2020-12-17-docker-testing.md
=> post/2020-12-17-docker-testing.md: change publish date

blog/content/post/2020-10-08-PCIe-features.md, blog/content/post/2020-11-30-coreboot_for_power.md, blog/content/post/2020-12-31-coreboot_for_power.md
=> blog/content/post/2020-11-30-coreboot_for_power.md: new post

blog/content/post/2021-01-13-IOMMU.md
Signed-off-by: Marek Kasiewicz <marek.kasiewicz@3mdeb.com>
=> blog/content/post/2021-01-13-IOMMU.md: Fix grammar

blog/content/post/2020-10-15-xen-implementation-for-trenchboot.md
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
=> 2020-10-15-xen-implementation-for-trenchboot.md: Fix problems

blog/content/post/2021-02-18-testing.md
=> post/2021-02-18-testing.md: change publish date and filename

blog/content/post/2021-02-16-fwupd-compilation-under-freebsd.md, blog/content/post/2021-03-15-fwupd-bsd-packages-and-ci.md
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
=> fwupd-bsd-packages-and-ci.md: Describe building packages

blog/content/post/2021-03-15-fwupd-bsd-packages-and-ci.md
=> post/2021-03-15-fwupd-bsd-packages-and-ci.md: fix series tag

blog/content/post/2021-04-22-what-is-yocto.md
=> post/2021-04-22-what-is-yocto.md: add post

blog/content/post/2021-04-30-right_to_repair.md
=> blog/content/post/2021-04-30-right_to_repair.md: update publish date

blog/content/post/2021-06-10-OSF_vs_OCP_OSF.md
=> post/2021-06-10-OSF_vs_OCP_OSF.md: change publish date

blog/content/post/2021-09-09-amd-milan-osf.md
=> post/2021-09-09-amd-milan-osf.md: fix description typo

blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
=> post/2021-12-14-secure-jtag-on-imx-soc.md: change publish state

blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
=> 2021-12-14-secure-jtag-on-imx-soc.md

blog/content/post/2021-12-10-fobnail_2nd_phase.md, blog/content/post/2021-12-15-fobnail_2nd_phase.md, blog/data/authors/tomasz.zyjewski.json
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
=> Fobnail blog post - 2 phase

blog/content/authors/tomasz-zyjewski/_index.md
=> authors/tomasz-zyjewski/_index.md: update profile bio

blog/themes/3mdeb/layouts/partials/footer.html
Signed-off-by: jakub.jeziorek <jakub.jeziorek@3mdeb.com>
=> footer.html: change company name

blog/content/post/2022-03-23-kgpe-d16-testing-update.md
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
=> blog/content/post/2022-03-23-kgpe-d16-testing-update.md: add blog post

blog/content/post/2022-05-17-fobnail_minimal_os.md
Proposition fo phase 9 section in blogpost
=> Fobnail phase 9

blog/content/post/2023-01-30-3mdeb-insights-winter-2023.md
=> post/2023-01-30-3mdeb-insights-winter-2023.md: change filename date

blog/content/post/2023-01-30-3mdeb-insights-winter-2023.md, blog/content/post/YYYY-MM-DD-template-post.md
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>
=> YYYY-MM-DD-template-post.md: Change call for action

blog/content/authors/dawid-zebacki/_index.md
Commit 1d896f5 changed name to Artur Kowalski and used links to his profile.
=> Fix Dawid Zębacki profile page

blog/content/authors/michal-iwanicki/_index.md, blog/data/authors/michal.iwanicki.json
Change job position to Trainee
=> Fix michal-iwanicki description

blog/content/post/2023-09-27-aem_phase2.md, blog/content/post/2023-12-14-aem_phase3.md, blog/content/post/2024-01-12-aem_phase3.md
Few TBDs left, mostly awaiting review, merging and creating a release for AEM components.
=> blog/content/post/2023-12-14-aem_phase3.md: add new post

blog/themes/3mdeb/layouts/authors/list.html
=> blog/themes/3mdeb/layouts/authors/list.html: remove redundant content

.github/workflows/seo.yml
For reason see https://github.com/3mdeb/news-and-ideas/issues/610#issue-2613535030
=> Fixes for SEO CI

blog/content/post/2025-02-20-conclusions-from-ram-data-remanence-tests.md
=> Added an introduction with links to prevoius two posts, added link to Power Up Privacy.

blog/content/post/2024-11-28-measured-boot-improvements.md, blog/content/post/2025-04-28-zarhusbmc.md, scripts/local-preview.sh
Add more references to ZarhusBMC post.
=> Zarhusbmc: Add more references
